environment: DEV

log:
  logger: zap
  level: DEBUG
  filename: ".logs/xrf197ilz.log"

application:
  port: 8009
  readTimeout: 7s
  idleTimeout: 30s
  writeTimeout: 10s
  gracefulTimeout: 15s

database:
  mongo:
    # Connection String Options
    # https://www.mongodb.com/docs/manual/reference/connection-string-options/#miscellaneous-configuration
    # https://www.mongodb.com/docs/manual/reference/connection-string-options/#miscellaneous-configuration
    # https://www.mongodb.com/docs/manual/reference/write-concern/#mongodb-writeconcern-writeconcern.-majority-
    w: majority
    retryWrites: false
    uri: LOCAL_MONGO_URI
    appName: mongosh+2.3.1
    databaseName: xrf0user
    directConnection: true
    cloudUri: CLOUD_MONGO_URI

security:
  passwordHash:
    time: 4
    thread: 3
    memory: 800
