environment: DEV

log:
  logger: zap
  level: DEBUG

rest:
  port: 8081

database:
  mongo:
    # Connection String Options
    # https://www.mongodb.com/docs/manual/reference/connection-string-options/#miscellaneous-configuration
    # https://www.mongodb.com/docs/manual/reference/connection-string-options/#miscellaneous-configuration
    # https://www.mongodb.com/docs/manual/reference/write-concern/#mongodb-writeconcern-writeconcern.-majority-
    w: majority
    retryWrites: false
    uri: LOCAL_MONGO_URI
    appName: mongosh+2.3.1
    databaseName: xrf0user
    directConnection: true
    cloudUri: CLOUD_MONGO_URI
