name: test

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master
      - develop

jobs:
  # This job execute 4 different builds for a combination of 2 (os) x 2 (go-versions) values.
  build:
    name: build and test
    runs-on: ${{ matrix.os }}

    strategy:
      # test on multiple operating systems and with different versions of Go
      matrix:
        os:
          - ubuntu-latest
#          - windows-latest
          - macos-latest
        go-version:
          - 1.22.x
          - 1.23.0

    steps:
      - name: Checkout source code onto a VM
        uses: actions/checkout@v4

      - name: Setup go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "go.sum"

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -o bin/cli -v ./cmd/cli/main.go

      - name: Test with go CLI
        run: go test ./... -json > testResults-go-${{ matrix.go-version }}.json

      - name: Upload build artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: xrf0-cli-build-artifact-${{ strategy.job-index }}-os-${{ matrix.os }}
          path: bin/cli

      - name: Upload Go test results for ${{ matrix.go-version }}
        uses: actions/upload-artifact@v4
        with:
          name: go-test-results-${{ strategy.job-index }}-go-${{ matrix.go-version }}
          path: testResults-go-${{ matrix.go-version }}.json
